### ISSUE TITLE
PkgFunctions::AddAuthData: This function and it's usage should be reviewed.

### ISSUE THREAD

**Issue by mlandres** [yast/yast-pkg-bindings#107]
https://github.com/yast/yast-pkg-bindings/blob/91e4896e7378e11a41258377a50e63cf8b025de7/src/Source_Get.cc#L439

It appears that the functions wants to add credentials to the `zypp::Url` argument, but the arg is  passed per value. So it's IMO a NO-OP.

**Comment by ancorgs** [comment]
I created a corresponding card to track this in the private trello board used by the YaST Team at SUSE to coordinate and prioritize: https://trello.com/c/heEyfvsv/4607-yast-pkg-bindings-pkgfunctionsaddauthdata-and-its-usage-should-be-reviewed

**Comment by lslezak** [comment]
It turned out the functionality is not needed anymore and we can remove the method. See more details in the #157 description.

Thank you for the report!
