### ISSUE TITLE
SourceEditSet (and other SourceFoo) not documented on Surge

### ISSUE THREAD

**Issue by mvidner** [yast/yast-pkg-bindings#137]
https://yast-pkg-bindings.surge.sh/ lists SourceEditSet but it does not link it to a description of the method even though the method [has some description](https://github.com/yast/yast-pkg-bindings/blob/03c80dcc8c11c7aa194dbe62a1686502ccb9d149/src/Source_Set.cc#L161).

We noted this while reviewing https://github.com/yast/yast-packager/pull/533

**Comment by ancorgs** [comment]
This seems to be corrected right now. Feel free to reopen if I'm mistaken.
